spring.datasource.url=jdbc:${DB_DRIVER}://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS}

spring.flyway.enabled=true

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none

security.jwt.secret-key=${JWT_SECRET_KEY}

management.endpoints.access.default=none
management.endpoint.health.access=unrestricted
management.endpoint.health.show-details=always
management.endpoint.prometheus.access=unrestricted
management.endpoint.loggers.access=unrestricted
management.endpoint.info.access=unrestricted
management.endpoints.web.exposure.include=health,prometheus,loggers,info
management.endpoints.web.base-path=/actuator
management.endpoints.web.cors.allowed-methods=GET,POST
management.endpoints.web.cors.allowed-origins=http://localhost
management.server.address=127.0.0.1
management.server.port=8279
management.info.git.mode=simple
management.info.git.enabled=true

resilience4j.circuitbreaker.instances.fetchTasksByUserId.minimum-number-of-calls=4
resilience4j.circuitbreaker.instances.fetchTasksByUserId.slidingWindowSize=8
resilience4j.circuitbreaker.instances.fetchTasksByUserId.wait-duration-in-open-state=60s
resilience4j.circuitbreaker.instances.fetchTasksByUserId.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.fetchTasksByUserId.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.fetchTasksByUserId.failure-rate-threshold=50
