spring.datasource.url=jdbc:${DB_DRIVER}://${DB_HOST}:${DB_PORT}/${DB_NAME}?ssl-mode=REQUIRED
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

security.jwt.secret-key=my_secret_key

spring.kafka.bootstrap-servers=${KAFKA_BROKERS}
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="avnadmin" password="${KAFKA_PASSWORD}";
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.ssl.truststore.location=security/kafka.truststore.jks
spring.kafka.properties.ssl.truststore.password=123456789

app.message_broker.name=kafka
app.topics.task_events=task_events

spring.cache.type=jcache
spring.cache.jcache.provider=com.hazelcast.cache.impl.HazelcastServerCachingProvider

spring.hazelcast.config=classpath:hazelcast.xml

spring.main.allow-bean-definition-overriding=true

management.endpoints.access.default=none
management.endpoint.health.access=unrestricted
management.endpoint.health.show-details=always
management.endpoint.prometheus.access=unrestricted
management.endpoint.loggers.access=unrestricted
management.endpoint.info.access=unrestricted
management.endpoints.web.exposure.include=health,prometheus,loggers,info
management.info.git.mode=full
management.info.git.enabled=true

resilience4j.circuitbreaker.instances.fetchTasksByUserId.minimum-number-of-calls=4
resilience4j.circuitbreaker.instances.fetchTasksByUserId.slidingWindowSize=8
resilience4j.circuitbreaker.instances.fetchTasksByUserId.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.fetchTasksByUserId.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.fetchTasksByUserId.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.fetchTasksByUserId.failure-rate-threshold=50

bucket4j.enabled=true

bucket4j.filters[0].cache-name=rate-limit-buckets
bucket4j.filters[0].url=/api/.*
bucket4j.filters[0].strategy=first
bucket4j.filters[0].http-response-body={ "status": 429, "error": "Too Many Requests", "message": "Rate limit exceeded. Retry after 1 minute." }

bucket4j.filters[0].rate-limits[0].cache-key=getRemoteAddr()
bucket4j.filters[0].rate-limits[0].bandwidths[0].capacity=10
bucket4j.filters[0].rate-limits[0].bandwidths[0].time=30
bucket4j.filters[0].rate-limits[0].bandwidths[0].unit=seconds
bucket4j.filters[0].rate-limits[0].bandwidths[0].refill-speed=interval
